package sk.karab.messaging;

public enum Message {


    PLACEHOLDER_VOTES_SO_FAR,
    PLACEHOLDER_VOTES_NEEDED,
    PLACEHOLDER_VOTES_LEFT,
    PLACEHOLDER_PINATA_EXISTS,
    PLACEHOLDER_PINATA_DOESNT_EXIST,
    PLACEHOLDER_PINATA_COUNT,
    PLACEHOLDER_UNKNOWN,

    HELP,
    PLAYER_ONLY,
    NO_PERMISSION,
    INVALID_NUMBER,
    ONLY_POSITIVE_NUMBERS,

    LOCATION_NAME_TOO_LONG,
    LOCATION_ADD_SUCCESS,
    LOCATION_ADD_FAILURE,
    LOCATION_REMOVE_SUCCESS,
    LOCATION_REMOVE_FAILURE,
    LOCATION_TP_SUCCESS,
    LOCATION_TP_FAILURE,
    LOCATION_LIST_HEADER,
    LOCATION_LIST_ENTRY,
    LOCATION_LIST_FOOTER,
    LOCATION_LIST_NOTHING_TO_SHOW,
    LOCATION_LIST_FAILURE,

    SPAWN_PLAYER_SUCCESS,
    SPAWN_LOCATION_SUCCESS,
    INVALID_LOCATION,

    VOTES_ADD_FAILURE,
    VOTES_REMOVE_FAILURE,
    VOTES_RESET_FAILURE,

    KILL_SUCCESS,
    STOP_SUCCESS


}
