package sk.karab.messaging;

public enum Message {


    HELP,
    PLAYER_ONLY,
    NO_PERMISSION,

    LOCATION_NAME_TOO_LONG,
    LOCATION_ADD_SUCCESS,
    LOCATION_ADD_FAILURE,
    LOCATION_REMOVE_SUCCESS,
    LOCATION_REMOVE_FAILURE,
    LOCATION_TP_SUCCESS,
    LOCATION_TP_FAILURE,
    LOCATION_LIST_HEADER,
    LOCATION_LIST_ENTRY,
    LOCATION_LIST_FOOTER,
    LOCATION_LIST_NOTHING_TO_SHOW,
    LOCATION_LIST_FAILURE,

    SPAWN_PLAYER_SUCCESS,
    SPAWN_LOCATION_SUCCESS,
    INVALID_LOCATION


}
